# Generated by Django 5.2.1 on 2025-05-08 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('food & beverage', 'Food & Beverage'), ('home goods', 'Home Goods'), ('books', 'Books'), ('toys & games', 'Toys & Games'), ('sporting goods', 'Sporting Goods'), ('health & beauty', 'Health & Beauty'), ('automotive', 'automotive')], default='Fashion', max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(upload_to='media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
