# Generated by Django 5.2.1 on 2025-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_model',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Food & Beverage', 'Food & Beverage'), ('Home Goods', 'Home Goods'), ('Books', 'Books'), ('Toys & Games', 'Toys & Games'), ('Sporting Goods', 'Sporting Goods'), ('Health & Beauty', 'Health & Beauty'), ('Automotive', 'automotive')], default='Fashion', max_length=20),
        ),
    ]
